/* Pokédex M7 v15.4.0 · Shop page + Expansions */
(function(){
  const nav=document.getElementById('m7AppNav');
  const wrap=document.querySelector('.wrap');
  const footer=wrap?.querySelector('.footer');
  if(!nav||!wrap||!footer)return;
  document.body.classList.add('m7-v154');

  const shopBtn=nav.querySelector('[data-app-nav="shop"]');
  const profileBtn=nav.querySelector('[data-app-nav="profile"]');

  let expansionsBtn=nav.querySelector('[data-app-nav="expansions"]');
  if(!expansionsBtn){
    expansionsBtn=document.createElement('button');
    expansionsBtn.type='button';
    expansionsBtn.className='m7-nav-btn';
    expansionsBtn.dataset.appNav='expansions';
    expansionsBtn.setAttribute('aria-label','Expansões');
    expansionsBtn.innerHTML='<svg viewBox="0 0 24 24"><path d="M4 7.5 12 4l8 3.5-8 3.5z"></path><path d="m4 12 8 3.5 8-3.5"></path><path d="m4 16.5 8 3.5 8-3.5"></path></svg><span>Expansões</span>';
    profileBtn?.before(expansionsBtn);
  }

  if(shopBtn){shopBtn.setAttribute('aria-label','Shop · Produtos e Stock');const label=shopBtn.querySelector('span:last-child');if(label)label.textContent='Shop'}

  const shopView=document.createElement('section');
  shopView.className='m7-v15-view m7-shop-view';
  shopView.id='m7ShopView';shopView.dataset.m7ViewPanel='shop';
  shopView.innerHTML='<div class="m7-inline-page-head"><div><span>SHOP</span><h2>Produtos / Stock</h2><p>Lojas, disponibilidade e notificações Push numa secção própria.</p></div></div><div class="m7-shop-host" id="m7ShopHost"><div class="m7-shop-loading">A preparar Produtos / Stock…</div></div>';
  footer.before(shopView);

  const expansionsView=document.createElement('section');
  expansionsView.className='m7-v15-view m7-expansions-view';
  expansionsView.id='m7ExpansionsView';expansionsView.dataset.m7ViewPanel='expansions';
  expansionsView.innerHTML=`<div class="m7-expansions-surface"><div class="m7-expansion-list-screen" id="m7ExpansionListScreen"><header class="m7-expansion-title"><h2>Expansões</h2></header><div class="m7-expansion-search"><span aria-hidden="true">⌕</span><input id="m7ExpansionQuery" autocomplete="off" placeholder="Buscar por Nome"></div><div class="m7-expansion-filters"><button class="m7-expansion-filter clear" id="m7ExpansionClear" type="button" aria-label="Limpar filtros">×</button><select id="m7ExpansionRegion" aria-label="Região"><option value="intl">🇺🇸 Internacional</option></select><select id="m7ExpansionSeries" aria-label="Era"><option value="all">▦ Era</option></select><select id="m7ExpansionType" aria-label="Tipo"><option value="all">▱ Tipo</option><option value="main">Principal</option><option value="special">Especial</option><option value="promo">Promos</option></select></div><div id="m7ExpansionSets"><div class="m7-expansion-loading">A carregar expansões…</div></div></div><div class="m7-expansion-detail-screen" id="m7ExpansionDetailScreen" hidden><div class="m7-expansion-detail-head"><button type="button" id="m7ExpansionBack" class="m7-expansion-back">‹</button><div class="m7-expansion-detail-logo"><img id="m7ExpansionDetailLogo" alt=""></div><div class="m7-expansion-detail-copy"><span id="m7ExpansionDetailSeries"></span><h2 id="m7ExpansionDetailName"></h2><p id="m7ExpansionDetailMeta"></p></div><div class="m7-expansion-detail-progress" id="m7ExpansionDetailProgress"><strong>0</strong><span>de 0</span></div></div><div class="m7-expansion-card-tools"><div class="m7-expansion-card-search"><span>⌕</span><input id="m7ExpansionCardQuery" placeholder="Pesquisar carta nesta expansão…"></div><select id="m7ExpansionOwnedFilter"><option value="all">Todas</option><option value="owned">Tenho</option><option value="missing">Em falta</option></select><select id="m7ExpansionSupertype"><option value="all">Todos os tipos</option><option value="Pokémon">Pokémon</option><option value="Trainer">Trainer</option><option value="Energy">Energy</option></select></div><div class="m7-expansion-card-grid" id="m7ExpansionCards"></div></div></div>`;
  footer.before(expansionsView);

  function esc(v){return typeof escapeHtml==='function'?escapeHtml(v):String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function norm(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'').trim()}
  function setActive(name){nav.querySelectorAll('[data-app-nav]').forEach(b=>b.classList.toggle('active',b.dataset.appNav===name));document.querySelectorAll('.m7-v15-view').forEach(v=>v.classList.toggle('active',v.dataset.m7ViewPanel===name));document.body.dataset.m7View=name;try{localStorage.setItem('pokedexm7-v15-view',name)}catch(_){}window.scrollTo({top:0,behavior:'auto'})}
  function clearCustom(){shopView.classList.remove('active');expansionsView.classList.remove('active')}
  nav.addEventListener('click',e=>{const b=e.target.closest('[data-app-nav]');if(!b)return;if(b.dataset.appNav!=='shop'&&b.dataset.appNav!=='expansions')setTimeout(clearCustom,0)});

  let shopMounted=false;
  function hideStockOverlay(){const modal=document.getElementById('stockModal');if(modal){modal.classList.add('m7-stock-detached');modal.classList.remove('open','show','active','visible');modal.setAttribute('aria-hidden','true');modal.style.display='none'}document.body.classList.remove('modal-open','stock-open')}
  function moveStockPanel(){const host=document.getElementById('m7ShopHost');if(!host)return false;const modal=document.getElementById('stockModal');const panel=modal?.querySelector('.stock-panel')||document.querySelector('.stock-panel');if(!panel)return false;panel.classList.add('m7-shop-page-panel');host.innerHTML='';host.appendChild(panel);hideStockOverlay();const close=document.getElementById('stockClose');if(close)close.setAttribute('aria-hidden','true');shopMounted=true;return true}
  function showShop(){setActive('shop');const already=moveStockPanel();try{if(typeof v124OpenStock==='function')v124OpenStock();else if(!already)document.getElementById('productStockBtn')?.click()}catch(_){}requestAnimationFrame(()=>{moveStockPanel();hideStockOverlay()});setTimeout(()=>{moveStockPanel();hideStockOverlay()},120)}
  nav.addEventListener('click',e=>{const b=e.target.closest('[data-app-nav="shop"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();showShop()},true);
  document.addEventListener('click',e=>{const b=e.target.closest('[data-v15-action="notifications"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();showShop();setTimeout(()=>document.getElementById('stockNotifyBtn')?.scrollIntoView({behavior:'smooth',block:'center'}),160)},true);
  const stockObserver=new MutationObserver(()=>{if(shopMounted){moveStockPanel();hideStockOverlay()}});const observeStock=()=>{const modal=document.getElementById('stockModal');if(modal)stockObserver.observe(modal,{attributes:true,childList:true,subtree:false})};observeStock();

  let allSets=[],visibleSets=[],currentSet=null,currentCards=[],setToken=0;
  const extraOwnedKey='pokedexm7-expansion-extra-owned-v1';
  function loadExtraOwned(){try{const a=JSON.parse(localStorage.getItem(extraOwnedKey)||'[]');return new Set(Array.isArray(a)?a.map(x=>String(x)):[])}catch(_){return new Set()}}
  function saveExtraOwned(set){try{localStorage.setItem(extraOwnedKey,JSON.stringify([...set]))}catch(_){}}
  let extraOwned=loadExtraOwned();
  function ownedRecords(){const out=[];const data=Array.isArray(window.__supabaseData)?window.__supabaseData:[];for(const row of data){const owned=row?.card_details?.owned;if(!owned||typeof owned!=='object')continue;for(const val of Object.values(owned)){if(!val||typeof val!=='object')continue;out.push({id:String(val.id||val.tcgdexOriginalId||''),name:String(val.name||''),number:String(val.number||''),setCode:String(val.setCode||''),setName:String(val.setName||'')})}}return out}
  function setMatchesOwned(set,rec){const ids=[set?.id,set?.ptcgoCode].map(norm).filter(Boolean);const names=[set?.name].map(norm).filter(Boolean);return ids.includes(norm(rec.setCode))||names.includes(norm(rec.setName))}
  function ownedCountForSet(set){const nums=new Set();for(const r of ownedRecords())if(setMatchesOwned(set,r))nums.add(`${norm(r.number)}|${norm(r.name)}`);for(const id of extraOwned){if(String(id).startsWith(`${set.id}::`))nums.add(String(id).slice(set.id.length+2))}return nums.size}
  function isCardOwned(card,set=currentSet){if(extraOwned.has(card.id))return true;const cid=norm(card.id),cnum=norm(card.number),cname=norm(card.name);return ownedRecords().some(r=>{if(norm(r.id)&&norm(r.id)===cid)return true;return setMatchesOwned(set,r)&&norm(r.number)===cnum&&(!r.name||norm(r.name)===cname)})}
  function setType(set){const s=norm(`${set?.name} ${set?.series}`);if(/promo|blackstar|gallery/.test(s))return 'promo';if(/special|holiday|fates|151|crownzenith|celebrations|pokemongo|prismatic|shrouded/.test(s))return 'special';return 'main'}
  function setTotal(set){return Number(set?.printedTotal||set?.total||0)}
  function setProgress(set){const total=setTotal(set),owned=Math.min(total||9999,ownedCountForSet(set));return {owned,total,pct:total?Math.max(0,Math.min(100,owned/total*100)):0}}
  function renderProgress(p){return `<span class="m7-set-count">${p.owned} de ${p.total||'—'}</span><span class="m7-set-ring" style="--p:${p.pct.toFixed(2)}"></span>`}
  function setLogo(set){return String(set?.images?.logo||'')}

  async function fetchSets(){const holder=document.getElementById('m7ExpansionSets');try{const r=await fetch('https://api.pokemontcg.io/v2/sets?orderBy=-releaseDate',{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const payload=await r.json();allSets=Array.isArray(payload?.data)?payload.data:[];const series=[...new Set(allSets.map(s=>String(s.series||'Outras')).filter(Boolean))];const select=document.getElementById('m7ExpansionSeries');select.innerHTML='<option value="all">▦ Era</option>'+series.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join('');applySetFilters()}catch(err){holder.innerHTML=`<div class="m7-expansion-error"><strong>Não foi possível carregar as expansões.</strong><span>${esc(err?.message||'Erro de ligação')}</span></div>`}}
  function applySetFilters(){const q=norm(document.getElementById('m7ExpansionQuery')?.value||''),series=String(document.getElementById('m7ExpansionSeries')?.value||'all'),type=String(document.getElementById('m7ExpansionType')?.value||'all');visibleSets=allSets.filter(s=>(!q||norm(`${s.name} ${s.ptcgoCode||''} ${s.id} ${s.series||''}`).includes(q))&&(series==='all'||String(s.series||'Outras')===series)&&(type==='all'||setType(s)===type));renderSetGroups()}
  function renderSetGroups(){const holder=document.getElementById('m7ExpansionSets');if(!visibleSets.length){holder.innerHTML='<div class="m7-expansion-empty">Nenhuma expansão encontrada.</div>';return}const groups=new Map();for(const set of visibleSets){const key=String(set.series||'Outras expansões');if(!groups.has(key))groups.set(key,[]);groups.get(key).push(set)}holder.innerHTML=[...groups.entries()].map(([series,sets])=>`<section class="m7-expansion-group"><h3>${esc(series)}</h3><div class="m7-expansion-set-grid">${sets.map(set=>{const p=setProgress(set);return `<button class="m7-expansion-set-card" type="button" data-set-id="${esc(set.id)}"><div class="m7-expansion-set-top"><span class="m7-expansion-code">${esc(set.ptcgoCode||set.id)}</span><span class="m7-expansion-countwrap">${renderProgress(p)}</span></div><div class="m7-expansion-set-logo">${setLogo(set)?`<img loading="lazy" src="${esc(setLogo(set))}" alt="${esc(set.name)}">`:`<span>${esc(set.name)}</span>`}</div><strong>${esc(set.name)}</strong></button>`}).join('')}</div></section>`).join('')}

  async function openSet(set){currentSet=set;currentCards=[];const token=++setToken;document.getElementById('m7ExpansionListScreen').hidden=true;document.getElementById('m7ExpansionDetailScreen').hidden=false;const logo=document.getElementById('m7ExpansionDetailLogo');logo.src=setLogo(set);logo.alt=set.name||'Expansão';document.getElementById('m7ExpansionDetailSeries').textContent=set.series||'Pokémon TCG';document.getElementById('m7ExpansionDetailName').textContent=set.name||'Expansão';document.getElementById('m7ExpansionDetailMeta').textContent=`${set.ptcgoCode||set.id} · ${set.releaseDate||''}`;updateDetailProgress();document.getElementById('m7ExpansionCards').innerHTML='<div class="m7-expansion-card-loading">A carregar cartas desta expansão…</div>';try{const select=encodeURIComponent('id,name,supertype,subtypes,rarity,number,artist,set,images,cardmarket,tcgplayer,nationalPokedexNumbers');const url=`https://api.pokemontcg.io/v2/cards?q=${encodeURIComponent(`set.id:${set.id}`)}&pageSize=250&orderBy=number&select=${select}`;const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json();if(token!==setToken)return;currentCards=Array.isArray(data?.data)?data.data:[];renderExpansionCards();updateDetailProgress()}catch(err){if(token!==setToken)return;document.getElementById('m7ExpansionCards').innerHTML=`<div class="m7-expansion-error"><strong>Não foi possível carregar as cartas.</strong><span>${esc(err?.message||'Erro de ligação')}</span></div>`}window.scrollTo({top:0,behavior:'auto'})}
  function updateDetailProgress(){if(!currentSet)return;const total=currentCards.length||setTotal(currentSet),owned=currentCards.length?currentCards.filter(c=>isCardOwned(c,currentSet)).length:ownedCountForSet(currentSet);const el=document.getElementById('m7ExpansionDetailProgress'),pct=total?owned/total*100:0;el.style.setProperty('--p',String(Math.max(0,Math.min(100,pct))));el.innerHTML=`<strong>${owned}</strong><span>de ${total||'—'}</span>`}
  function filteredCards(){const q=norm(document.getElementById('m7ExpansionCardQuery')?.value||''),own=String(document.getElementById('m7ExpansionOwnedFilter')?.value||'all'),supertype=String(document.getElementById('m7ExpansionSupertype')?.value||'all');return currentCards.filter(card=>{const o=isCardOwned(card,currentSet);return (!q||norm(`${card.name} ${card.number} ${card.rarity||''}`).includes(q))&&(own==='all'||(own==='owned'?o:!o))&&(supertype==='all'||String(card.supertype||'')===supertype)})}
  function renderExpansionCards(){const grid=document.getElementById('m7ExpansionCards'),rows=filteredCards();if(!rows.length){grid.innerHTML='<div class="m7-expansion-empty">Nenhuma carta corresponde a estes filtros.</div>';return}grid.innerHTML=rows.map(card=>{const owned=isCardOwned(card,currentSet),image=card?.images?.small||card?.images?.large||'';return `<article class="m7-expansion-card ${owned?'owned':'missing'}" data-card-id="${esc(card.id)}"><button type="button" class="m7-expansion-card-preview" data-preview-card="${esc(card.id)}"><span class="m7-expansion-card-status">${owned?'✓ TENHO':'EM FALTA'}</span><div class="m7-expansion-card-image"><img loading="lazy" src="${esc(image)}" alt="${esc(card.name||'Carta')}"></div><div class="m7-expansion-card-copy"><strong>${esc(card.name||'Carta')}</strong><span>#${esc(card.number||'—')} · ${esc(card.rarity||card.supertype||'Carta')}</span></div></button><button type="button" class="m7-expansion-card-action ${owned?'owned':''}" data-manage-card="${esc(card.id)}">${owned?'Gerir':'Adicionar'}</button></article>`}).join('')}
  function pokemonFor(card){const ids=(card?.nationalPokedexNumbers||[]).map(Number).filter(Boolean),all=Array.isArray(window.__all)?window.__all:[];return all.find(p=>ids.includes(Number(p.id)))||all.find(p=>norm(p?.name)===norm(card?.name))||null}
  async function manageCard(card){const pokemon=pokemonFor(card);if(pokemon){try{if(typeof openVariantModal==='function')await openVariantModal(card,pokemon);else if(typeof openArtModal==='function')await openArtModal(pokemon)}catch(_){try{if(typeof openArtModal==='function')openArtModal(pokemon)}catch(__){}}setTimeout(()=>{renderExpansionCards();updateDetailProgress();renderSetGroups()},180);return}if(extraOwned.has(card.id))extraOwned.delete(card.id);else extraOwned.add(card.id);saveExtraOwned(extraOwned);renderExpansionCards();updateDetailProgress();renderSetGroups()}

  const preview=document.createElement('div');preview.className='m7-expansion-preview';preview.id='m7ExpansionPreview';preview.setAttribute('aria-hidden','true');preview.innerHTML='<div class="m7-expansion-preview-panel"><button class="m7-expansion-preview-close" type="button" id="m7ExpansionPreviewClose">×</button><img id="m7ExpansionPreviewImage" alt=""><div class="m7-expansion-preview-copy"><span id="m7ExpansionPreviewSet"></span><h3 id="m7ExpansionPreviewName"></h3><p id="m7ExpansionPreviewMeta"></p><button type="button" id="m7ExpansionPreviewManage">Adicionar / gerir</button></div></div>';document.body.appendChild(preview);let previewCard=null;
  function openPreview(card){previewCard=card;document.getElementById('m7ExpansionPreviewImage').src=card?.images?.large||card?.images?.small||'';document.getElementById('m7ExpansionPreviewImage').alt=card?.name||'Carta';document.getElementById('m7ExpansionPreviewSet').textContent=currentSet?.name||card?.set?.name||'Expansão';document.getElementById('m7ExpansionPreviewName').textContent=card?.name||'Carta';document.getElementById('m7ExpansionPreviewMeta').textContent=`#${card?.number||'—'} · ${card?.rarity||card?.supertype||'Carta'} · ${isCardOwned(card,currentSet)?'Tenho':'Em falta'}`;document.getElementById('m7ExpansionPreviewManage').textContent=isCardOwned(card,currentSet)?'Gerir carta':'Adicionar à coleção';preview.classList.add('open');preview.setAttribute('aria-hidden','false');document.body.classList.add('modal-open')}
  function closePreview(){preview.classList.remove('open');preview.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');previewCard=null}
  document.getElementById('m7ExpansionPreviewClose')?.addEventListener('click',closePreview);preview.addEventListener('click',e=>{if(e.target===preview)closePreview()});document.getElementById('m7ExpansionPreviewManage')?.addEventListener('click',async()=>{const c=previewCard;closePreview();if(c)await manageCard(c)});

  nav.addEventListener('click',e=>{const b=e.target.closest('[data-app-nav="expansions"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();setActive('expansions');if(!allSets.length)fetchSets();else renderSetGroups()},true);
  document.getElementById('m7ExpansionSets')?.addEventListener('click',e=>{const b=e.target.closest('[data-set-id]');if(!b)return;const set=allSets.find(s=>String(s.id)===String(b.dataset.setId));if(set)openSet(set)});
  document.getElementById('m7ExpansionBack')?.addEventListener('click',()=>{setToken++;currentSet=null;currentCards=[];document.getElementById('m7ExpansionDetailScreen').hidden=true;document.getElementById('m7ExpansionListScreen').hidden=false;renderSetGroups();window.scrollTo({top:0,behavior:'auto'})});
  document.getElementById('m7ExpansionQuery')?.addEventListener('input',applySetFilters);document.getElementById('m7ExpansionSeries')?.addEventListener('change',applySetFilters);document.getElementById('m7ExpansionType')?.addEventListener('change',applySetFilters);document.getElementById('m7ExpansionClear')?.addEventListener('click',()=>{document.getElementById('m7ExpansionQuery').value='';document.getElementById('m7ExpansionSeries').value='all';document.getElementById('m7ExpansionType').value='all';applySetFilters()});
  ['m7ExpansionCardQuery','m7ExpansionOwnedFilter','m7ExpansionSupertype'].forEach(id=>{const el=document.getElementById(id);el?.addEventListener(id==='m7ExpansionCardQuery'?'input':'change',renderExpansionCards)});
  document.getElementById('m7ExpansionCards')?.addEventListener('click',async e=>{const previewBtn=e.target.closest('[data-preview-card]'),manageBtn=e.target.closest('[data-manage-card]'),id=String((manageBtn||previewBtn)?.dataset.manageCard||(manageBtn||previewBtn)?.dataset.previewCard||'');if(!id)return;const card=currentCards.find(c=>String(c.id)===id);if(!card)return;if(manageBtn)await manageCard(card);else openPreview(card)});
  const syncEl=document.getElementById('syncText');if(syncEl)new MutationObserver(()=>{if(expansionsView.classList.contains('active')){renderSetGroups();if(currentCards.length){renderExpansionCards();updateDetailProgress()}}}).observe(syncEl,{subtree:true,childList:true,characterData:true});
  fetchSets();
})();